/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FreelancerMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PLATFORM_FEE_BPS"
      | "applyForJob"
      | "calculatePlatformFee"
      | "cancelJob"
      | "createJob"
      | "escrow"
      | "feeRecipient"
      | "getJobSummary"
      | "jobs"
      | "markCompleted"
      | "nextJobId"
      | "releasePayment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FreelancerAssigned"
      | "JobCancelled"
      | "JobCompleted"
      | "JobCreated"
      | "PaymentReleased"
      | "PlatformFeePaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyForJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "createJob", values: [string]): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getJobSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "markCompleted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextJobId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJobSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextJobId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
}

export namespace FreelancerAssignedEvent {
  export type InputTuple = [jobId: BigNumberish, freelancer: AddressLike];
  export type OutputTuple = [jobId: bigint, freelancer: string];
  export interface OutputObject {
    jobId: bigint;
    freelancer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    refundedAmount: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    refundedAmount: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    refundedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [jobId: BigNumberish];
  export type OutputTuple = [jobId: bigint];
  export interface OutputObject {
    jobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    description: string,
    netPrice: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    description: string,
    netPrice: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    description: string;
    netPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    freelancer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, freelancer: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    freelancer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeePaidEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    recipient: AddressLike,
    fee: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, recipient: string, fee: bigint];
  export interface OutputObject {
    jobId: bigint;
    recipient: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FreelancerMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): FreelancerMarketplace;
  waitForDeployment(): Promise<this>;

  interface: FreelancerMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  applyForJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  calculatePlatformFee: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  cancelJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  createJob: TypedContractMethod<[description: string], [void], "payable">;

  escrow: TypedContractMethod<[], [string], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getJobSummary: TypedContractMethod<
    [jobId: BigNumberish],
    [
      [string, string, boolean, bigint, bigint, boolean] & {
        client: string;
        freelancer: string;
        completed: boolean;
        totalAmount: bigint;
        escrowedAmount: bigint;
        paymentReleased: boolean;
      }
    ],
    "view"
  >;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean, boolean] & {
        id: bigint;
        client: string;
        freelancer: string;
        description: string;
        price: bigint;
        completed: boolean;
        paid: boolean;
      }
    ],
    "view"
  >;

  markCompleted: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextJobId: TypedContractMethod<[], [bigint], "view">;

  releasePayment: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "applyForJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculatePlatformFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<[description: string], [void], "payable">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getJobSummary"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [
      [string, string, boolean, bigint, bigint, boolean] & {
        client: string;
        freelancer: string;
        completed: boolean;
        totalAmount: bigint;
        escrowedAmount: bigint;
        paymentReleased: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean, boolean] & {
        id: bigint;
        client: string;
        freelancer: string;
        description: string;
        price: bigint;
        completed: boolean;
        paid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markCompleted"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextJobId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "FreelancerAssigned"
  ): TypedContractEvent<
    FreelancerAssignedEvent.InputTuple,
    FreelancerAssignedEvent.OutputTuple,
    FreelancerAssignedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeePaid"
  ): TypedContractEvent<
    PlatformFeePaidEvent.InputTuple,
    PlatformFeePaidEvent.OutputTuple,
    PlatformFeePaidEvent.OutputObject
  >;

  filters: {
    "FreelancerAssigned(uint256,address)": TypedContractEvent<
      FreelancerAssignedEvent.InputTuple,
      FreelancerAssignedEvent.OutputTuple,
      FreelancerAssignedEvent.OutputObject
    >;
    FreelancerAssigned: TypedContractEvent<
      FreelancerAssignedEvent.InputTuple,
      FreelancerAssignedEvent.OutputTuple,
      FreelancerAssignedEvent.OutputObject
    >;

    "JobCancelled(uint256,address,uint256)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobCompleted(uint256)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobCreated(uint256,address,string,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "PlatformFeePaid(uint256,address,uint256)": TypedContractEvent<
      PlatformFeePaidEvent.InputTuple,
      PlatformFeePaidEvent.OutputTuple,
      PlatformFeePaidEvent.OutputObject
    >;
    PlatformFeePaid: TypedContractEvent<
      PlatformFeePaidEvent.InputTuple,
      PlatformFeePaidEvent.OutputTuple,
      PlatformFeePaidEvent.OutputObject
    >;
  };
}
